### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by samuelgoddard** [Negan1911/storybook-css-modules-preset#11]
Hey, trying to get this working in a storybook project and getting the following error after following the instructions:

ERR! TypeError: Cannot read property 'toString' of undefined
ERR!     at /Users/samgoddard/code/xxx/node_modules/storybook-css-modules-preset/index.js:13:51
ERR!     at Array.filter (<anonymous>)
ERR!     at Object.webpackFinal (/Users/samgoddard/code/xxx/node_modules/storybook-css-modules-preset/index.js:13:32)

Any idea what I might be doing wrong?

**Comment by sklawren** [comment]
I just debugged this. It's due to Storybook 6.2 having an empty object in the array of rules. It's a simple fix. I'm going to make a PR right now.

**Comment by sklawren** [comment]
@Negan1911 My PR is ready to go.

**Comment by nalejandroveron** [comment]
Nice! i'll review and merge :)

**Comment by nalejandroveron** [comment]
You can download version `1.0.8` with this fix applied

**Comment by samuelgoddard** [comment]
Thank you so much both!! 🎉
