### ISSUE TITLE
 Cannot read property 'use' of undefined

### ISSUE THREAD

**Issue by Kazimirkas** [Negan1911/storybook-css-modules-preset#13]
Storybook 6.2.9

ERR! TypeError: Cannot read property 'use' of undefined
ERR!     at Object.webpackFinal (...node_modules/storybook-css-modules-preset/index.js:21:24)

**Comment by nalejandroveron** [comment]
I may need a repo example, I think that maybe this plugin is conflicting with some other you have installed

**Comment by clintandrewhall** [comment]
I'm getting this, too, using Create React App.  I'll likely have an example later today, or this week.  You might be able to repro by creating a new CRA, then `npx sb init`, and then add the rule to `main.js`...?

**Comment by nalejandroveron** [comment]
I'll give it a shot!

**Comment by clintandrewhall** [comment]
FWIW, while there's an investigation: this solved the issue for me.

https://github.com/storybookjs/storybook/issues/2320#issuecomment-351804807

**Comment by Kazimirkas** [comment]
> I may need a repo example, I think that maybe this plugin is conflicting with some other you have installed

I am also using the CRA and also the following addons `  addons: [
    "storybook-css-modules-preset",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/preset-create-react-app",
    "@storybook/addon-a11y",
  ],`
Nothing special else. FYI, I am not using SCSS

**Comment by Kazimirkas** [comment]
<img width="484" alt="Screenshot 2021-04-26 at 09 02 05" src="https://user-images.githubusercontent.com/15028496/116035687-168ec200-a66e-11eb-9851-7adbc815b216.png">

**Comment by Kazimirkas** [comment]
<img width="478" alt="Screenshot 2021-04-26 at 09 03 19" src="https://user-images.githubusercontent.com/15028496/116035781-43db7000-a66e-11eb-8dc2-ccad4a59dfce.png">

**Comment by Kazimirkas** [comment]
<img width="476" alt="Screenshot 2021-04-26 at 09 04 04" src="https://user-images.githubusercontent.com/15028496/116035843-5d7cb780-a66e-11eb-941f-db5597615507.png">

**Comment by Kazimirkas** [comment]
@Negan1911 I Sorry, I was not attentive. CSS modules are working with the storybook and RCA under the hood already because of RCA webpack configuration. No need of additional addons. You may close the issue
