### ISSUE TITLE
1.1 breaks build due to unknown option in CSS Loader

### ISSUE THREAD

**Issue by thien-do** [Negan1911/storybook-css-modules-preset#15]
*Reproducible repo:*
- Clone https://github.com/moaijs/moai
- "cd core" then "yarn storybook" -> success
- "yarn add <this_package@1.1.0" then "yarn storybook" -> error

I guess this is because of https://github.com/Negan1911/storybook-css-modules-preset/commit/065ad14e5c21e05a8480c35a954272d15ecdd631

```
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'presetsList'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals?, esModule? }
    at validate (/home/thien/Code/moai/core/node_modules/css-loader/node_modules/schema-utils/dist/validate.js:98:11)
```

Full screenshot:

![image](https://user-images.githubusercontent.com/5953369/117536664-93367e80-b026-11eb-9c01-e09596641e1a.png)

**Comment by nalejandroveron** [comment]
Thanks, there was a bad commit and it was reverted on 1.1.1
