### ISSUE TITLE
How to get with Global Styles to work without direct import?

### ISSUE THREAD

**Issue by mechadragon01** [Negan1911/storybook-css-modules-preset#17]
Option 1: import `common.module.css` in  Component file `Button.tsx` - Doesn't work
`Button.tsx`
```typescript
import React from 'react';
import common from  '../../styles/common.module.css';
import styles from './Button.module.css';

export interface ButtonProps {
  children?: React.ReactNode;
}

const Button = ({
  children,
}: ButtonProps) => {

  return (
    <button className={common['p2-semi-bold']}>
      {children}
    </button>
  );
};

export default Button;
```

Option 2: import `common.module.css` in  `Button.module.css` - Doesn't work.
`Button.module.css`
```css
@import '../../styles/common.module.css';
```

Option 3: import regular `common.css` in  `Button.tsx` - Doesn't work.
`Button.tsx`
```typescript
import React from 'react';
import  '../../styles/common.css';
import styles from './Button.module.css';

export interface ButtonProps {
  children?: React.ReactNode;
}

const Button = ({
  children,
}: ButtonProps) => {

  return (
    <button className='p2-semi-bold'>
      {children}
    </button>
  );
};

export default Button;
```

Can't seem to get any global styling to work unless I import the style directly
`import typography from '../../styles/tokens/typography.module.css';`

I have lots of nested css files and importing directly from the class is not feasible.

**Comment by nalejandroveron** [comment]
I'm not quite sure if I'm understanding, if you want global styles you should not end the files in `.module.css`, that may be the reason
