### ISSUE TITLE
1.0.3 breaks my storybook config styles

### ISSUE THREAD

**Issue by glomotion** [Negan1911/storybook-css-modules-preset#4]
So I recently tried upgrading to from 1.0.2 to 1.0.3 and all the modular styles seemed to get broken. I'm running pretty much stock standard storybook config, with your preset addon. 

```
// .storybook/main.js

module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-knobs',
    'storybook-css-modules-preset',
  ],
};
```

dep versions: 
```
"@storybook/addon-actions": "^6.0.28",
"@storybook/addon-essentials": "^6.0.28",
"@storybook/addon-knobs": "^6.0.28",
"@storybook/addon-links": "^6.0.28",
"@storybook/react": "^6.0.28",
"storybook-css-modules-preset": "^1.0.3",
```

**Comment by glomotion** [comment]
my guess is this regex change broke the css-loader's rules for detecting css module files: 
https://github.com/Negan1911/storybook-css-modules-preset/commit/77860b22e8617deaf06188dd542cbe0a22ef1011

**Comment by nalejandroveron** [comment]
Thanks for the issue, i'll downgrade and investigate a way to cover both issues!
