### ISSUE TITLE
I can't get CSS modules to work with what is explained in readme

### ISSUE THREAD

**Issue by eggei** [Negan1911/storybook-css-modules-preset#6]
Hi there, thanks for this preset.
I am trying to get it to work with my React-TS application, however, event tough I am using CSS modules w/o any problem it doesn't work for me in Storybook. Am I missing something?

```json
// package.json
"storybook-css-modules-preset": "^1.0.4"
```

```javascript
// .storybook/main.js

module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    'storybook-css-modules-preset',
  ],
};
```

```javascript
// Relevant part of webpack.config.js
{
          test: /\.css$/,
          use: [
            {
              loader: MiniCssExtractPlugin.loader,
              options: {
                hmr: process.env.NODE_ENV === appConfig.env.DEV,
              },
            },
            {
              loader: 'css-loader',
              options: {
                modules: {
                  context: path.resolve(__dirname, 'src'),
                  mode: 'local',
                  hashPrefix: `cc${Date.now()}`,
                  localIdentName:
                    process.env.NODE_ENV === appConfig.env.DEV
                      ? '[name]__[local]'
                      : '[hash:base64]',
                  exportGlobals: true,
                },
              },
            },
            {
              loader: 'postcss-loader',
            },
          ],
}
```

I import css modules like this:
```javascript
import classNames from 'some.module.css'

<div className={classNames.someClass} />
```
`classNames.someClass` is `undefined` after setting up `storybook-css-modules-preset`

**Comment by nalejandroveron** [comment]
So, couple of things here that might be the problem.
- Is your webpack config from storybook or the actual app? This is actually planned as a preset, if you want to use your own custom webpack config for storybook you might not need this preset at all.
- Check out that you're not correctly importing your module (`./some.module.css` vs `some.module.css`)

If you have some time, please check with 1.0.5 and, if persists, please create a small repro repo for me and I'll be more than happy to take a look!

**Comment by eggei** [comment]
Thank you very much for the response! `1.0.5` resolved this issue, it works now 🥳 

Just for the records:
- I am **not** using a custom webpack config for storybook that is separate than the main webpack config. I have one webpack config in the root folder and was trying to use this preset to transfer that css modules handler to storybook.
- I apologize for the typo there it is actually `./some.module.css` but I did a typo when writing it in here.

**Comment by rxliuli** [comment]
I ran into the same problem, the smallest repo @eggei 

https://github.com/rxliuli/storybook_css_module_example

**Comment by rxliuli** [comment]
In the end, I solved this problem by customizing webpack

```js
module.exports = {
    webpackFinal(config = {}, options = {}) {
        const css_regex = '/\\.css$/'
        const cssRule = config.module.rules.find(_ => _.test.toString() === css_regex)

        return {
            ...config,
            module: {
                ...config.module,
                rules: [
                    ...config.module.rules.filter(_ => _.test.toString() !== css_regex),
                    {
                        ...cssRule,
                        exclude: /\.module\.css$/,
                    },
                    {
                        ...cssRule,
                        test: /\.module\.css$/,
                        use: [
                            'style-loader',
                            {
                                loader: 'css-loader',
                                options: {
                                    importLoaders: 1,
                                    modules: true,
                                },
                            },
                        ],
                    },
                ],
            },
        }
    },
    stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
    addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
}
```

**Comment by nalejandroveron** [comment]
Hey @rxliuli your reproduction repo is up and public? getting 404 when trying to access it...

**Comment by rxliuli** [comment]
> Hey @rxliuli your reproduction repo is up and public? getting 404 when trying to access it...

Sorry, it contains some company content, I just deleted it and uploaded it again
